file = open("NewFile.txt", 'w')

writing_file = "This is the content which is written on the file" \
               "\nHello Bootstrap"
writeFile = file.write(writing_file) 
file.close()  
file = open("NewFile.txt", "r")
print(file.read())  
file.close()  
print()
file = open("NewFile.txt", "r")
print(file.readlines())  
file.close() 
print()
file = open("NewFile.txt", "r")
print(file.readline())  
print(file.readline(5)) 
file.close()  
file = open("NewFile.txt", 'r')
print(len(file.read()))  
file.close()  
file = open("NewFile.txt", 'r')
print(len(file.readlines()))  
file.close()  
